name = "lukseh-dev"
main = "worker.js"
compatibility_date = "2024-01-01"

[env.production]
name = "lukseh-dev"

# Environment variables
[vars]
ENVIRONMENT = "production"

# Routes to handle (uncomment when you have a custom domain)
# routes = [
#   { pattern = "lukseh.dev/*", zone_name = "lukseh.dev" }
# ]
